---
- hosts: all
  become: yes
  roles:
     - hostname          # Set hostname and change /etc/hosts file
     - firewall_selinux  # Disable firewall and SELINUX
     - ipa-pkgs          # Install Free IPA server Packages
     - ipaserver-install # Configure Free IPA server
